### PR TITLE
Update and rename bold.md to icceddev.md

### PR DESCRIPTION
**Pull request by urbantumbleweed**
Just want to include iceddev on this cool project.

### CODE REVIEW

**Comment by bradwestfall** [comment]
hmm, rivalry? :)

**Comment by bradwestfall** [comment]
I just added iced dev manually so we don't override bold :)

**Comment by urbantumbleweed** [comment]
Sorry about that.  Next time I'll stick to the tried and true method of forking, adding a file, and pull requesting.  Thanks.

**Comment by bradwestfall** [comment]
No problem, keeping me on my toes!

**Pull request closed without merging**
