### PR TITLE
nir cohen md

### PR DESCRIPTION
**Pull request by thenir**
please add me

### CODE REVIEW

**Comment by thenir** [comment]
Thanks for this Brad

**Comment by bradwestfall** [comment]
No problem bud. But with the file you changed. I see it has your name but it has all my information

**Comment by thenir** [comment]
Really that's funny I will fix it thanks

On Sunday, June 14, 2015, Brad Westfall notifications@github.com wrote:

> No problem bud. But with the file you changed. I see it has your name but
> it has all my information
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bradwestfall/webdevphoenix/pull/59#issuecomment-111892489
> .

## 

Sent from Gmail Mobile

**Comment by thenir** [comment]
Ok I fixed it

**Comment by bradwestfall** [comment]
Thanks bud

**Pull request merged**
