### PR TITLE
Added profile for Skyhook Interactive

### PR DESCRIPTION
**Pull request by corycrowley**

### CODE REVIEW

**Comment by bradwestfall** [comment]
Thank you

**Comment by corycrowley** [comment]
Hi there! I don't see our company on the site. Is there something we are missing? Let me know. Thanks!!

**Comment by bradwestfall** [comment]
We had renamed the variable "company" to be "company_name". You probably did your fork before that or something. I just got it fixed for you. Sorry I didn't notice when I merged

**Comment by corycrowley** [comment]
No worries! Thanks!!

**Pull request merged**
